AG-30908 clean node_modules
Merge in ADGUARD-FILTERS/vscode-adblock-syntax from fix/AG-30908 to master

Squashed commit of the following:

commit 1971b053f61e5159ced75e5f9f4851d49e93cd4b
Author: scripthunter7 <d.tota@adguard.com>
Date:   Wed Mar 6 15:03:32 2024 +0100

    cleanup second deploy

commit f180365adf6ec5a3b0852fa9c51b23abe6172a57
Author: scripthunter7 <d.tota@adguard.com>
Date:   Wed Mar 6 15:03:05 2024 +0100

    add comment

commit 86606c325debed967cb55a3912dada5a21e3cf50
Author: scripthunter7 <d.tota@adguard.com>
Date:   Wed Mar 6 15:01:08 2024 +0100

    clean node_modules

diff --git a/bamboo-specs/build.yaml b/bamboo-specs/build.yaml
--- a/bamboo-specs/build.yaml
+++ b/bamboo-specs/build.yaml
@@ -72,11 +72,6 @@ Build:
 
             # Create build.txt file with version
             yarn build:txt
-
-            # Cleanup
-            rm -rf node_modules
-            rm -rf client/node_modules
-            rm -rf server/node_modules
     - inject-variables:
         file: out/build.txt
         scope: RESULT
@@ -86,6 +81,31 @@ Build:
         configuration:
           selectedRepository: defaultRepository
           tagName: v${bamboo.inject.version}
+  final-tasks:
+    - script:
+        interpreter: SHELL
+        scripts:
+          - |-
+            set -x
+            set -e
+
+            # Fix mixed logs
+            exec 2>&1
+
+            ls -la
+
+            echo "Size before cleanup:" && du -h | tail -n 1
+            
+            # cleanup root directory
+            rm -rf node_modules
+
+            # cleanup client directory
+            rm -rf client/node_modules
+
+            # cleanup server directory
+            rm -rf server/node_modules
+  
+            echo "Size after cleanup:" && du -h | tail -n 1
   # Store the .vsix file as a build artifact
   artifacts:
     - name: vscode-adblock.vsix
diff --git a/bamboo-specs/deploy.yaml b/bamboo-specs/deploy.yaml
--- a/bamboo-specs/deploy.yaml
+++ b/bamboo-specs/deploy.yaml
@@ -42,9 +42,28 @@ marketplace.visualstudio.com:
 
             # https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publish-an-extension
             yarn vsce publish -p ${bamboo.vsceToken} -i vscode-adblock.vsix
+  final-tasks:
+    - script:
+        interpreter: SHELL
+        scripts:
+          - |-
+            set -x
+            set -e
 
-            # Cleanup
+            # Fix mixed logs
+            exec 2>&1
+
+            ls -la
+
+            echo "Size before cleanup:" && du -h | tail -n 1
+            
+            # cleanup root directory
+            # note: no need to clean client and server directories here, because we only installed
+            #       dependencies in the root directory (for the vsce publish command above)
+            # TODO: switch to yarn workspaces
             rm -rf node_modules
+  
+            echo "Size after cleanup:" && du -h | tail -n 1
   requirements:
     - adg-docker: 'true'
   notifications:
@@ -89,9 +108,28 @@ open-vsx.org:
 
             # https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#5-package-and-upload
             yarn ovsx publish vscode-adblock.vsix -p ${bamboo.openVsxToken}
+  final-tasks:
+    - script:
+        interpreter: SHELL
+        scripts:
+          - |-
+            set -x
+            set -e
 
-            # Cleanup
+            # Fix mixed logs
+            exec 2>&1
+
+            ls -la
+
+            echo "Size before cleanup:" && du -h | tail -n 1
+            
+            # cleanup root directory
+            # note: no need to clean client and server directories here, because we only installed
+            #       dependencies in the root directory (for the vsce publish command above)
+            # TODO: switch to yarn workspaces
             rm -rf node_modules
+  
+            echo "Size after cleanup:" && du -h | tail -n 1
   requirements:
     - adg-docker: 'true'
   notifications:
diff --git a/bamboo-specs/test.yaml b/bamboo-specs/test.yaml
--- a/bamboo-specs/test.yaml
+++ b/bamboo-specs/test.yaml
@@ -64,13 +64,31 @@ Build:
 
             # Run Jest tests
             yarn test
-
-            # Cleanup
-            rm -rf node_modules
-            rm -rf client/node_modules
-            rm -rf server/node_modules
   final-tasks:
-    - clean
+    - script:
+        interpreter: SHELL
+        scripts:
+          - |-
+            set -x
+            set -e
+
+            # Fix mixed logs
+            exec 2>&1
+
+            ls -la
+
+            echo "Size before cleanup:" && du -h | tail -n 1
+            
+            # cleanup root directory
+            rm -rf node_modules
+
+            # cleanup client directory
+            rm -rf client/node_modules
+
+            # cleanup server directory
+            rm -rf server/node_modules
+  
+            echo "Size after cleanup:" && du -h | tail -n 1
   requirements:
     - adg-docker: true
 
